

language: php

php:
  - 5.3
  - 5.4

before_script:
    - wget http://getcomposer.org/composer.phar
    - php composer.phar install

# composer install
# echo 'date.timezone = "Europe/Paris"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
